- hosts: localhost
  become: yes
  tasks:
  - name: install tomcat
    apt:
     name: tomcat8
     state: present
     update_cache: yes
  - name : install apache2
    apt:
      name: apache2
      state: present
